name: Create Q1_archive_README

on:
  push:
    branches:
      - main

jobs:
  create-archive:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Copy README.md to Q1_archive_README.md
      run: cp README.md Q1_archive_README.md

    - name: Commit changes
      run: |
        git config --global user.name "${{ secrets.GIT_USER_NAME }}"
        git config --global user.email "${{ secrets.GIT_USER_EMAIL }}"
        git add Q1_archive_README.md
        git commit -m "Add Q1_archive_README.md copied from README.md"
        git push origin main
