name: Create Q2_archive_README

on:
  push:
    branches:
      - main

jobs:
  create-archive:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Create Q2_archive_README.md
      run: |
        echo "Nom et Prénom: Caron Antoine" > Q2_archive_README.md
        echo "Date et Heure d'exécution: $(date)" >> Q2_archive_README.md
        echo -e "\nContenu de README.md:\n" >> Q2_archive_README.md
        cat README.md >> Q2_archive_README.md

    - name: Commit changes
      run: |
        git config --global user.name ToiViMic
        git config --global user.email toivimic.caron@gmail.com
        git add Q2_archive_README.md
        git commit -m "Add Q2_archive_README.md with execution details"
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
