name: Create Q4_archive_date

on:
  push:
    branches:
      - main

jobs:
  create-archive:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Get current date
      id: date
      run: echo "date=$(date +'%d-%m-%Y')" >> $GITHUB_ENV

    - name: Pull latest changes from remote
      run: |
        git pull origin main --rebase

    - name: Create Q4_archive_date.txt
      run: |
        ARCHIVE_FILE="Q4_archive_${{ env.date }}.txt"
        echo "Nom et Prénom: Caron Antoine" > $ARCHIVE_FILE
        echo -e "\nContenu de Q4.java:\n" >> $ARCHIVE_FILE
        cat Q4.java >> $ARCHIVE_FILE

    - name: Commit changes
      run: |
        git config --global user.name ToiViMic
        git config --global user.email toivimic.caron@gmail.com
        git add Q4.java Q4_archive_*.txt
        git commit -m "Add Q4_archive_${{ env.date }}.txt with Q4.java content"
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
